name: run main

# shell to use
defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  getads:
    name: get ads
    runs-on: ubuntu-latest
    steps:
      
      # checkout the branch to prevent conflicts
      - name: Checkout Branch
        uses: actions/checkout@v2
        
      # installs python 3.8
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      # install the required packages
      - name: Install Packages
        run: |
          pip install fbchat
          
      # run the python file
      - name: Run
        run: python main.py
        env:
          EMAIL: ${{ secrets.EMAIL }}   
          PASSWORD: ${{ secrets.PASSWORD }}  
